SlotAnchor
Player SlotAnchor.Player
SlotType SlotAnchor.M_SlotType
Referenced by MouseHoverComponent_OnMouseDragEnterImmediately.
GameObject SlotAnchor.OnHoverShowGO
Referenced by HideHoverShowGO, ShowHoverGO.
ModuleRetinue SlotAnchor.M_ModuleRetinue
void SlotAnchor.Awake()
void SlotAnchor.Start()
void SlotAnchor.Update()
void SlotAnchor.ShowHoverGO()
References OnHoverShowGO.
Referenced by MouseHoverComponent_OnMouseDragEnterImmediately.
void SlotAnchor.HideHoverShowGO()
References OnHoverShowGO.
Referenced by MouseHoverComponent_OnMouseDragLeaveImmediately, MouseHoverComponent_OnMouseLeaveImmediately.
void SlotAnchor.MouseHoverComponent_OnMouseDragEnterImmediately(Vector3 mousePosition)
此接口用于将除了MouseHoverComponent通用效果之外的效果还给调用者自行处理
References DragManager.CurrentDrag, DragManager.DM, M_SlotType, ShowHoverGO.
void SlotAnchor.MouseHoverComponent_OnMouseEnterImmediately(Vector3 mousePosition)
void SlotAnchor.MouseHoverComponent_OnMouseEnter(Vector3 mousePosition)
void SlotAnchor.MouseHoverComponent_OnMouseOver()
void SlotAnchor.MouseHoverComponent_OnMouseLeave()
void SlotAnchor.MouseHoverComponent_OnMouseLeaveImmediately()
References HideHoverShowGO.
void SlotAnchor.MouseHoverComponent_OnMouseDragLeaveImmediately()
References HideHoverShowGO.