DragComponent
int DragComponent.retinuesLayer
可拖动功能，应用于卡片、人物、技能、随从、 实现拖动过程中卡牌跟随鼠标的一段动画 如果被拖动物体带target效果，则此组件只实现最初的卡牌跟随鼠标动画，由targetArrow终结此过程
Referenced by Awake, checkMoveTorRetinue.
int DragComponent.boardAreasLayer
Referenced by Awake, checkAreas.
int DragComponent.slotsLayer
Referenced by Awake, checkMoveToSlot.
IDragComponent DragComponent.caller
Referenced by Awake.
bool DragComponent.canDrag
Referenced by Update.
bool DragComponent.hasTarget
Referenced by Update.
float DragComponent.dragDistance
Referenced by Update.
bool DragComponent.isOnDrag
bool DragComponent.isBegin
Referenced by Update.
Vector3 DragComponent.dragBeginPosition
Referenced by Update.
Quaternion DragComponent.dragBeginQuaternion
Referenced by Update.
Vector3 DragComponent.dragLastPosition
Referenced by Update.
Arrow DragComponent.arrow
Referenced by Update.
bool DragComponent.IsOnDrag
Referenced by Update.
void DragComponent.Awake()
References boardAreasLayer, caller, retinuesLayer, slotsLayer.
void DragComponent.Start()
void DragComponent.Update()
References arrow, canDrag, checkAreas, checkMoveTorRetinue, checkMoveToSlot, dragBeginPosition, dragBeginQuaternion, dragDistance, dragLastPosition, hasTarget, isBegin, IsOnDrag.
BoardAreaTypes DragComponent.checkAreas()
References boardAreasLayer, EnemyBattleGroundArea, EnemyHandArea, Others, SelfBattleGroundArea, SelfHandArea.
Referenced by Update.
List<SlotAnchor> DragComponent.checkMoveToSlot()
References slotsLayer.
Referenced by Update.
ModuleRetinue DragComponent.checkMoveTorRetinue()
References retinuesLayer.
Referenced by Update.