ModuleBase
GameObjectPool ModuleBase.gameObjectPool
Referenced by ModuleShield.Awake, ModuleWeapon.Awake, ModuleRetinue.Awake.
Player ModuleBase.Player
Referenced by ModuleRetinue.Initiate.
CardInfo_Base ModuleBase.CardInfo
Referenced by ModuleShield.GetCurrentCardInfo, ModuleWeapon.GetCurrentCardInfo, ModuleRetinue.GetCurrentCardInfo, Initiate, ModuleRetinue.On_ShieldChanged, ModuleRetinue.On_WeaponChanged, ShowCardDetail.
CardInfo_Base ModuleBase.ModuleCurrentCardInfo
Referenced by ModuleShield.GetCurrentCardInfo, ModuleWeapon.GetCurrentCardInfo, ModuleRetinue.GetCurrentCardInfo.
float ModuleBase.DetailCardSize
Referenced by ShowCardDetail.
float ModuleBase.DetailCardModuleSize
Referenced by ShowCardDetail.
float ModuleBase.DetailCardSize_Retinue
Referenced by ShowCardDetail.
Card ModuleBase.detailCard
Referenced by HideCardDetail, ShowCardDetail.
Card ModuleBase.detailCard_Weapon
Referenced by HideCardDetail, ShowCardDetail.
Card ModuleBase.detailCard_Shield
Referenced by HideCardDetail, ShowCardDetail.
Card ModuleBase.detailCard_Pack
Referenced by HideCardDetail.
Card ModuleBase.detailCard_MA
Referenced by HideCardDetail.
virtual void ModuleBase.PoolRecycle()
Referenced by ModuleShield.ArmorBeAttacked, ModuleShield.ShieldBeAttacked.
virtual void ModuleBase.Initiate(CardInfo_Base cardInfo, Player player)
References CardInfo.
abstract CardInfo_Base ModuleBase.GetCurrentCardInfo()
void ModuleBase.DragComponent_OnMouseDown()
此接口用于将除了DragComponent通用效果之外的效果还给调用者自行处理
void ModuleBase.DragComponent_OnMousePressed(BoardAreaTypes boardAreaType, List< SlotAnchor > slotAnchors, ModuleRetinue moduleRetinue)
传达鼠标左键按住拖动时的鼠标位置信息
boardAreaType 移动到了战场的哪个区域 slotAnchors 移动到了哪个slot上 moduleRetinue 移动到了哪个随从上
virtual void ModuleBase.DragComponent_OnMouseUp(BoardAreaTypes boardAreaType, List< SlotAnchor > slotAnchors, ModuleRetinue moduleRetinue, Vector3 dragLastPosition, Vector3 dragBeginPosition, Quaternion dragBeginQuaternion)
传达鼠标左键松开时的鼠标位置信息
boardAreaType 移动到了战场的哪个区域 slotAnchors 移动到了哪个slot上 moduleRetinue 移动到了哪个随从上 dragLastPosition 移动的最后位置 dragBeginPosition 移动的初始位置 dragBeginQuaternion 被拖动对象的初始旋转
virtual void ModuleBase.DragComponent_SetStates(ref bool canDrag, ref bool hasTarget)
virtual float ModuleBase.DragComponnet_DragDistance()
void ModuleBase.MouseHoverComponent_OnMouseDragEnterImmediately(Vector3 mousePosition)
此接口用于将除了MouseHoverComponent通用效果之外的效果还给调用者自行处理
virtual void ModuleBase.MouseHoverComponent_OnMouseEnterImmediately(Vector3 mousePosition)
virtual void ModuleBase.MouseHoverComponent_OnMouseEnter(Vector3 mousePosition)
References ShowCardDetail.
virtual void ModuleBase.MouseHoverComponent_OnMouseOver()
virtual void ModuleBase.MouseHoverComponent_OnMouseLeave()
References HideCardDetail.
virtual void ModuleBase.MouseHoverComponent_OnMouseLeaveImmediately()
void ModuleBase.MouseHoverComponent_OnMouseDragLeaveImmediately()
void ModuleBase.DragComponent_SetHasTarget(ref bool hasTarget)
void ModuleBase.DragComponnet_DragOutEffects()
void ModuleBase.Start()
void ModuleBase.Update()
void ModuleBase.ShowCardDetail(Vector3 mousePosition)
References GameBoardManager.CardDetailPreview, CardInfo, CardInfo_Base.CardType, detailCard, detailCard_Shield, detailCard_Weapon, DetailCardModuleSize, DetailCardSize, DetailCardSize_Retinue, GameBoardManager.GBM, Card.InstantiateCardByCardInfo, Shield, Weapon.
Referenced by MouseHoverComponent_OnMouseEnter.
void ModuleBase.HideCardDetail()
References detailCard, detailCard_MA, detailCard_Pack, detailCard_Shield, detailCard_Weapon.
Referenced by MouseHoverComponent_OnMouseLeave.
void ModuleBase.initiateNumbers(ref GameObject Number, ref CardNumberSet cardNumberSet, NumberSize numberType, CardNumberSet.TextAlign textAlign, GameObject block)
Referenced by ModuleRetinue.On_ShieldChanged, ModuleRetinue.On_ShieldDown, ModuleRetinue.On_ShieldEquiped, ModuleRetinue.On_WeaponChanged, ModuleRetinue.On_WeaponDown, ModuleRetinue.On_WeaponEquiped.
void ModuleBase.initiateNumbers(ref GameObject Number, ref CardNumberSet cardNumberSet, NumberSize numberType, CardNumberSet.TextAlign textAlign, GameObject block, char firstSign)