RoundManager
RoundManager RoundManager.rm
RoundManager RoundManager.RM
int RoundManager.RoundNumber
Player RoundManager.CurrentPlayer
Referenced by BeginRound, Start, switchPlayer.
GameObject RoundManager.SelfTurnText
GameObject RoundManager.EnemyTurnText
Vector3 RoundManager.selfTurnText_DefaultPosition
Referenced by Awake, BeginRound.
Vector3 RoundManager.enemyTurnText_DefaultPosition
Referenced by Awake, BeginRound.
Vector3 RoundManager.farAwayPosition
Referenced by Awake, BeginRound.
void RoundManager.Awake()
References enemyTurnText_DefaultPosition, farAwayPosition, selfTurnText_DefaultPosition.
void RoundManager.Start()
References BeginRound, CurrentPlayer, GameManager.EnemyPlayer, HandManager.GetACardByID, GameManager.GM, Player.MyHandManager, GameManager.SelfPlayer, switchPlayer.
void RoundManager.Update()
void RoundManager.switchPlayer()
References CurrentPlayer.
Referenced by OnEndRoundButtonClick, Start.
void RoundManager.BeginRound()
References CurrentPlayer, enemyTurnText_DefaultPosition, farAwayPosition, GameManager.GM, GameManager.SelfPlayer, selfTurnText_DefaultPosition.
Referenced by OnEndRoundButtonClick, Start.
void RoundManager.EndRound()
Referenced by OnEndRoundButtonClick.
void RoundManager.OnEndRoundButtonClick()
References BeginRound, EndRound, switchPlayer.