HandManager
Player HandManager.Player
Referenced by DrawCard, DrawRetinueCard, GetACardByID.
float [] HandManager.anglesDict
Referenced by Awake, RefreshCardsPlace.
float [] HandManager.horrizonDistanceDict
Referenced by Awake, RefreshCardsPlace.
List<Card> HandManager.cards
Referenced by Awake, BeginRound, DropFirstCard, EndRound, RefreshAllCardUsable, RefreshCardsPlace.
int HandManager.retinueLayer
Referenced by Awake.
int HandManager.cardLayer
Referenced by Awake, CheckMousePosition.
Quaternion HandManager.defaultCardRotation
Referenced by becomeBigger, RefreshCardsPlace.
bool HandManager.isSet_defaultCardRotation
Referenced by RefreshCardsPlace.
Vector3 HandManager.defaultCardPosition
Referenced by RefreshCardsPlace.
bool HandManager.isSet_defaultCardPosition
Referenced by RefreshCardsPlace.
Card HandManager.currentFocusCard
Referenced by CardColliderReplaceOnMouseExit, CardOnMouseEnter, CheckMousePosition.
bool HandManager.isBeginDrag
Referenced by becomeBigger, BeginDrag, CheckMousePosition, EndDrag, returnToSmaller.
int HandManager.cardNumber
Referenced by DrawCard, DrawRetinueCard, DropCard, GetACardByID, RefreshCardsPlace.
float HandManager.HandCardSize
Referenced by RefreshCardsPlace.
float HandManager.PullOutCardSize
Referenced by becomeBigger.
void HandManager.Awake()
References anglesDict, cardLayer, cards, horrizonDistanceDict, retinueLayer.
void HandManager.Start()
void HandManager.Update()
References CheckMousePosition.
void HandManager.CheckMousePosition()
References cardLayer, currentFocusCard, isBeginDrag, returnToSmaller.
Referenced by Update.
void HandManager.becomeBigger(Card focusCard)
References GameManager.CanTestEnemyCards, defaultCardRotation, GameManager.GM, isBeginDrag, PullOutCardSize, Player.WhichPlayer.
Referenced by CardOnMouseEnter.
void HandManager.returnToSmaller(Card lostFocusCard)
References GameManager.CanTestEnemyCards, GameManager.GM, isBeginDrag, RefreshCardsPlace, Player.WhichPlayer.
Referenced by CardColliderReplaceOnMouseExit, CardOnMouseEnter, CheckMousePosition.
void HandManager.DrawCards(int number)
References DrawCard.
void HandManager.DrawCard()
References cardNumber, Player, RefreshCardsPlace.
Referenced by DrawCards.
void HandManager.GetACardByID(int cardID)
References cardNumber, Player, RefreshCardsPlace.
Referenced by RoundManager.Start.
void HandManager.DrawRetinueCard()
References cardNumber, Player, RefreshCardsPlace.
void HandManager.DropFirstCard()
References cards, DropCard.
void HandManager.DropCard(Card dropCard)
References cardNumber, RefreshCardsPlace.
Referenced by DropFirstCard.
void HandManager.RefreshCardsPlace()
References anglesDict, GameManager.CanTestEnemyCards, cardNumber, cards, defaultCardPosition, defaultCardRotation, GameManager.GM, HandCardSize, horrizonDistanceDict, isSet_defaultCardPosition, isSet_defaultCardRotation, Player.WhichPlayer.
Referenced by DrawCard, DrawRetinueCard, DropCard, GetACardByID, returnToSmaller.
void HandManager.RefreshAllCardUsable()
References cards, Player.CostLeft.
void HandManager.CardOnMouseEnter(Card focusCard)
References becomeBigger, currentFocusCard, returnToSmaller.
void HandManager.CardColliderReplaceOnMouseExit(Card lostFocusCard)
References currentFocusCard, returnToSmaller.
void HandManager.BeginDrag()
References isBeginDrag.
void HandManager.EndDrag()
References isBeginDrag.
void HandManager.BeginRound()
References cards.
void HandManager.EndRound()
References cards.