Card
GameObjectPool Card.gameObjectPool
Referenced by Card_Shield.Awake, Card_Weapon.Awake, Card_Retinue.Awake.
GameObject Card.GoNumberSet_Cost
Referenced by Initiate.
CardNumberSet Card.CardNumberSet_Cost
Referenced by Initiate.
Player Card.Player
Referenced by Card_Retinue.summonRetinue, Card_Shield.summonShield, Card_Weapon.summonWeapon.
CardInfo_Base Card.CardInfo
Referenced by Card_Shield.Initiate, Card_Weapon.Initiate, Card_Retinue.Initiate, Initiate, Card_Retinue.summonRetinue, Card_Shield.summonShield, Card_Weapon.summonWeapon.
ColliderReplace Card.myColliderReplace
Referenced by ResetColliderAndReplace.
BoxCollider Card.myCollider
Referenced by Awake, ResetColliderAndReplace.
bool Card.Usable
Referenced by DragComponent_SetStates.
GameObject Card.Block_Cost
Referenced by Initiate.
Renderer Card.PictureBoxRenderer
Referenced by Initiate.
int Card.m_Cost
int Card.M_Cost
Referenced by DragComponent_OnMouseUp, Initiate.
virtual void Card.PoolRecycle()
References ResetColliderAndReplace.
Referenced by Card_Shield.summonShield, Card_Weapon.summonWeapon.
virtual void Card.Initiate(CardInfo_Base cardInfo, Player player)
References Block_Cost, CardInfo, CardNumberSet_Cost, GoNumberSet_Cost, initiateNumbers, M_Cost, PictureBoxRenderer.
virtual void Card.OnBeginRound()
virtual void Card.OnEndRound()
void Card.DragComponent_OnMouseDown()
此接口用于将除了DragComponent通用效果之外的效果还给调用者自行处理
virtual void Card.DragComponent_OnMousePressed(BoardAreaTypes boardAreaType, List< SlotAnchor > slotAnchors, ModuleRetinue moduleRetinue)
传达鼠标左键按住拖动时的鼠标位置信息
boardAreaType 移动到了战场的哪个区域 slotAnchors 移动到了哪个slot上 moduleRetinue 移动到了哪个随从上
virtual void Card.DragComponent_OnMouseUp(BoardAreaTypes boardAreaType, List< SlotAnchor > slotAnchors, ModuleRetinue moduleRetinue, Vector3 dragLastPosition, Vector3 dragBeginPosition, Quaternion dragBeginQuaternion)
传达鼠标左键松开时的鼠标位置信息
boardAreaType 移动到了战场的哪个区域 slotAnchors 移动到了哪个slot上 moduleRetinue 移动到了哪个随从上 dragLastPosition 移动的最后位置 dragBeginPosition 移动的初始位置 dragBeginQuaternion 被拖动对象的初始旋转
References M_Cost.
virtual void Card.DragComponent_SetStates(ref bool canDrag, ref bool hasTarget)
References Usable.
virtual float Card.DragComponnet_DragDistance()
void Card.DragComponnet_DragOutEffects()
References GameObjectPool.GameObjectPoolPosition.
virtual void Card.Awake()
References myCollider.
void Card.initiateNumbers(ref GameObject Number, ref CardNumberSet cardNumberSet, NumberSize numberType, CardNumberSet.TextAlign textAlign, GameObject block)
Referenced by Initiate.
void Card.initiateNumbers(ref GameObject Number, ref CardNumberSet cardNumberSet, NumberSize numberType, CardNumberSet.TextAlign textAlign, GameObject block, char firstSign)
void Card.Start()
void Card.Update()
void Card.OnMouseEnter()
static Card Card.InstantiateCardByCardInfo(CardInfo_Base cardInfo, Transform parent, Player player)
References CardInfo_Base.CardType.
Referenced by ModuleBase.ShowCardDetail.
void Card.ResetColliderAndReplace()
References myCollider, myColliderReplace.
Referenced by PoolRecycle.