//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCardGameCommon.GamePlay.Card {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCardGameCommon.GamePlay.Card.CardResource", typeof(CardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AllCards&gt;
        ///    &lt;Card id=&quot;999&quot;&gt;
        ///        &lt;CardInfo name=&quot;baseInfo&quot; cardName=&quot;空牌&quot; cardDesc=&quot;&quot; cost=&quot;0&quot; dragPurpose=&quot;Summon&quot; cardType=&quot;Retinue&quot; cardColor=&quot;#787878&quot; hightLightColor=&quot;#FFFF00&quot;/&gt;
        ///        &lt;CardInfo name=&quot;upgradeInfo&quot; upgradeCardID=&quot;-1&quot; cardLevel=&quot;0&quot; /&gt;
        ///        &lt;CardInfo name=&quot;lifeInfo&quot; life=&quot;0&quot; totalLife=&quot;0&quot; /&gt;
        ///        &lt;CardInfo name=&quot;battleInfo&quot; basicAttack=&quot;0&quot; basicShield=&quot;0&quot; basicArmor=&quot;0&quot; isSodier=&quot;False&quot; /&gt;
        ///        &lt;CardInfo name=&quot;slotInfo&quot; slot1=&quot;N [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;AllSideEffects&gt;
        ///  &lt;SideEffect id=&quot;0&quot; name=&quot;KillAllInBattleGround&quot; desc=&quot;破坏所有{0}&quot;&gt;
        ///    &lt;params name=&quot;IsNeedChoise&quot; type=&quot;bool&quot;&gt;&lt;/params&gt;
        ///    &lt;params name=&quot;M_TargetRange&quot; type=&quot;enum&quot;&gt;&lt;/params&gt;
        ///  &lt;/SideEffect&gt;
        ///  &lt;SideEffect id=&quot;1&quot; name=&quot;AddLifeForSomeRetinue&quot; desc=&quot;使一个{0}增加{1}点生命&quot;&gt;
        ///    &lt;params name=&quot;IsNeedChoise&quot; type=&quot;bool&quot;&gt;&lt;/params&gt;
        ///    &lt;params name=&quot;M_TargetRange&quot; type=&quot;enum&quot;&gt;&lt;/params&gt;
        ///    &lt;params name=&quot;Value&quot; type=&quot;int&quot;&gt;&lt;/params&gt;
        ///  &lt;/SideEffect&gt;
        ///  &lt;SideE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SideEffects {
            get {
                return ResourceManager.GetString("SideEffects", resourceCulture);
            }
        }
    }
}
