BattleGroundManager
bool BattleGroundManager.BattleGroundIsFull
Referenced by AddRetinue, RemoveRetinue, Card_Retinue.summonRetinue.
Player BattleGroundManager.Player
Vector3 BattleGroundManager._defaultRetinuePosition
Referenced by RefreshBattleGround.
int BattleGroundManager._maxRetinueNumber
Referenced by AddRetinue, Initiate, RemoveRetinue.
int BattleGroundManager._retinueCount
Referenced by AddRetinue, AddRetinueByPosition, CheckRetinueOnPosition, RefreshBattleGround, RemoveRetinue.
float BattleGroundManager._retinueInterval
Referenced by AddRetinueByPosition, CheckRetinueOnPosition, RefreshBattleGround.
List<ModuleRetinue> BattleGroundManager._retinues
Referenced by BeginRound, CheckRetinueOnPosition, EndRound, RefreshBattleGround, RemoveRetinue.
void BattleGroundManager.Awake()
References Initiate.
void BattleGroundManager.Start()
void BattleGroundManager.Update()
void BattleGroundManager.Initiate()
References _maxRetinueNumber.
Referenced by Awake.
void BattleGroundManager.AddRetinueByPosition(ModuleRetinue newRetinue, Vector3 dragLastPosition)
References _retinueCount, _retinueInterval, AddRetinue.
ModuleRetinue BattleGroundManager.CheckRetinueOnPosition(Vector3 dragLastPosition)
References _retinueCount, _retinueInterval, _retinues.
void BattleGroundManager.AddRetinue(ModuleRetinue newRetinue, int index)
References _maxRetinueNumber, _retinueCount, BattleGroundIsFull, RefreshBattleGround.
Referenced by AddRetinueByPosition.
void BattleGroundManager.RemoveRetinue(ModuleRetinue retinue)
References _maxRetinueNumber, _retinueCount, _retinues, BattleGroundIsFull, RefreshBattleGround.
void BattleGroundManager.RefreshBattleGround()
References _defaultRetinuePosition, _retinueCount, _retinueInterval, _retinues.
Referenced by AddRetinue, RemoveRetinue.
void BattleGroundManager.BeginRound()
References _retinues.
void BattleGroundManager.EndRound()
References _retinues.