CardDeck
CardDeckInfo CardDeck.M_CardDeckInfo
本类中封装卡组操作的基本功能
Referenced by CardDeck.
bool CardDeck.IsEmpty
Referenced by checkEmpty, CardDeckManager.DrawRetinueCard, CardDeckManager.DrawTop.
bool CardDeck.IsAbandonCardsEmpty
Referenced by checkEmpty.
List<CardInfo_Base> CardDeck.Cards
Referenced by CardDeck, DrawCardOnTop, DrawCardsOnTop, FindATypeOfCard< CardInfo_Type >, FindATypeOfCards< CardInfo_Type >, GetARetinueCardToTheTop, GetFirstCardInfo, GetTopCardsInfo, SuffleSelf.
List<CardInfo_Base> CardDeck.AbandonCards
Referenced by AbandonCardRecycle.
void CardDeck.checkEmpty()
References IsAbandonCardsEmpty, IsEmpty.
Referenced by AbandonCardRecycle, AddCardToButtom, CardDeck, DrawCardOnTop, DrawCardsOnTop.
CardDeck.CardDeck(CardDeckInfo cdi)
References Cards, checkEmpty, M_CardDeckInfo, SuffleSelf.
CardInfo_Type CardDeck.FindATypeOfCard< CardInfo_Type >()
References Cards.
List<CardInfo_Type> CardDeck.FindATypeOfCards< CardInfo_Type >(int cardNumber)
References Cards.
CardInfo_Base CardDeck.DrawCardOnTop()
References Cards, checkEmpty.
List<CardInfo_Base> CardDeck.DrawCardsOnTop(int cardNumber)
References Cards, checkEmpty.
void CardDeck.AddCardToButtom(CardInfo_Base newCard)
References checkEmpty.
CardInfo_Base CardDeck.GetFirstCardInfo()
References Cards.
List<CardInfo_Base> CardDeck.GetTopCardsInfo(int cardNumber)
References Cards.
void CardDeck.SuffleSelf()
References Cards, Suffle.
Referenced by CardDeck.
void CardDeck.GetARetinueCardToTheTop()
References Cards, CardInfo_Base.CardType.
void CardDeck.AbandonCardRecycle()
References AbandonCards, checkEmpty, Suffle.
static void CardDeck.Suffle(List< CardInfo_Base > targetCardList)
Referenced by AbandonCardRecycle, SuffleSelf.